swagger: "2.0"
info:
  version: "1.0.0"
  title: "drunk"
  description: "drunk api"
host: "localhost:1234"
basePath: "/"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /liquor:
    get:
      operationId: getLiquors
      responses:
        '200':
          description: Success
          schema:
            type: "array"
            items:
              $ref: '#/definitions/getLiquorResponseParams'
    post:
      operationId: addLiquor
      consumes:
         - multipart/form-data
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          $ref: '#/definitions/addLiquorRequestParams'
      responses:
        '201':
          description: Created
        '400':
          description: Failed
  /LiquorImage/{fileName}:
    get:
      produces:
        - image/png
      parameters:
      - in: path
        name: fileName
        description: image file name
        required: true
        type: "string"
      responses:
        '200':
          description: Success
          schema:
            type: "file"
        '400':
          description: Failed
definitions:
  addLiquorRequestParams:
    type: "object"
    properties:
      name:
        type: "string"
        example: "beer"
      fileName:
        type: "string"
        example: "beer.png"
      image:
        type: "string"
        format: "binary"
  getLiquorResponseParams:
    type: "object"
    properties:
      ID:
        type: "string"
        example: "0"
      Name:
        type: "string"
        example: "beer"
      ImageFilePath:
        type: "string"
        example: "LiquorImage/example.png"
      UpdatedAt:
        type: "string"
        format: "date"
        example: "2020-05-02T12:14:57.830568+09:00"
        
